# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doing_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(618, 115)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 0, 1, 5)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cancel.sizePolicy().hasHeightForWidth())
        self.pushButton_cancel.setSizePolicy(sizePolicy)
        self.pushButton_cancel.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.pushButton_cancel.setText("")
        self.pushButton_cancel.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 1, 4, 1, 1)
        self.pushButton_stop_play = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_stop_play.sizePolicy().hasHeightForWidth())
        self.pushButton_stop_play.setSizePolicy(sizePolicy)
        self.pushButton_stop_play.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.pushButton_stop_play.setText("")
        self.pushButton_stop_play.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_stop_play.setObjectName("pushButton_stop_play")
        self.gridLayout.addWidget(self.pushButton_stop_play, 1, 3, 1, 1)
        self.lineEdit_progress = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_progress.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_progress.setFont(font)
        self.lineEdit_progress.setFrame(False)
        self.lineEdit_progress.setObjectName("lineEdit_progress")
        self.gridLayout.addWidget(self.lineEdit_progress, 1, 0, 1, 3)
        self.lineEdit_doing = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_doing.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_doing.setFont(font)
        self.lineEdit_doing.setFrame(False)
        self.lineEdit_doing.setObjectName("lineEdit_doing")
        self.gridLayout.addWidget(self.lineEdit_doing, 0, 0, 1, 5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
