# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'number_instance.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Button(QtWidgets.QLineEdit):

	def __init__(self, parent):
		super(Button, self).__init__(parent)

		self.setAcceptDrops(True)

	def dragEnterEvent(self, e):

		if e.mimeData().hasUrls():
			e.accept()
		else:
			super(Button, self).dragEnterEvent(e)

	def dragMoveEvent(self, e):

		super(Button, self).dragMoveEvent(e)

	def dropEvent(self, e):

		if e.mimeData().hasUrls():
			for url in e.mimeData().urls():
				self.setText(os.path.normcase(url.toLocalFile()))
				e.accept()
		else:
			super(Button, self).dropEvent(e)


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(468, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_number_instance = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_number_instance.setFont(font)
        self.label_number_instance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_number_instance.setObjectName("label_number_instance")
        self.gridLayout.addWidget(self.label_number_instance, 2, 0, 1, 1)
        self.pushButton_new = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_new.sizePolicy().hasHeightForWidth())
        self.pushButton_new.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_new.setFont(font)
        self.pushButton_new.setObjectName("pushButton_new")
        self.gridLayout.addWidget(self.pushButton_new, 1, 5, 1, 1)
        self.lineEdit_path_new = Button(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_path_new.sizePolicy().hasHeightForWidth())
        self.lineEdit_path_new.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_path_new.setFont(font)
        self.lineEdit_path_new.setObjectName("lineEdit_path_new")
        self.gridLayout.addWidget(self.lineEdit_path_new, 1, 1, 1, 4)
        self.pushButton_old = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_old.sizePolicy().hasHeightForWidth())
        self.pushButton_old.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_old.setFont(font)
        self.pushButton_old.setObjectName("pushButton_old")
        self.gridLayout.addWidget(self.pushButton_old, 0, 5, 1, 1)
        self.label_new = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_new.sizePolicy().hasHeightForWidth())
        self.label_new.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_new.setFont(font)
        self.label_new.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_new.setObjectName("label_new")
        self.gridLayout.addWidget(self.label_new, 1, 0, 1, 1)
        self.label_old = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_old.sizePolicy().hasHeightForWidth())
        self.label_old.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_old.setFont(font)
        self.label_old.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_old.setObjectName("label_old")
        self.gridLayout.addWidget(self.label_old, 0, 0, 1, 1)
        self.lineEdit_path_old = Button(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_path_old.sizePolicy().hasHeightForWidth())
        self.lineEdit_path_old.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_path_old.setFont(font)
        self.lineEdit_path_old.setObjectName("lineEdit_path_old")
        self.gridLayout.addWidget(self.lineEdit_path_old, 0, 1, 1, 4)
        self.pushButton_create = QtWidgets.QPushButton(Dialog)
        self.pushButton_create.setObjectName("pushButton_create")
        self.gridLayout.addWidget(self.pushButton_create, 3, 3, 1, 3)
        self.lineEdit_number_instance = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_number_instance.setFont(font)
        self.lineEdit_number_instance.setObjectName("lineEdit_number_instance")
        self.gridLayout.addWidget(self.lineEdit_number_instance, 2, 1, 1, 5)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 3, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Экземпляр документов"))
        self.label_number_instance.setText(_translate("Dialog", "Номер(а)"))
        self.pushButton_new.setText(_translate("Dialog", "Открыть"))
        self.pushButton_old.setText(_translate("Dialog", "Открыть"))
        self.label_new.setText(_translate("Dialog", "Конечные"))
        self.label_old.setText(_translate("Dialog", "Исходные"))
        self.pushButton_create.setText(_translate("Dialog", "Создать"))
        self.lineEdit_number_instance.setText(_translate("Dialog", "2"))
        self.pushButton_cancel.setText(_translate("Dialog", "Отмена"))
