# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Print_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(502, 282)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_folfer_name = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_folfer_name.setFont(font)
        self.label_folfer_name.setObjectName("label_folfer_name")
        self.gridLayout_2.addWidget(self.label_folfer_name, 0, 0, 1, 1)
        self.label_folder = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_folder.setFont(font)
        self.label_folder.setText("")
        self.label_folder.setObjectName("label_folder")
        self.gridLayout_2.addWidget(self.label_folder, 0, 1, 1, 1)
        self.label_state_name = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_state_name.setFont(font)
        self.label_state_name.setObjectName("label_state_name")
        self.gridLayout_2.addWidget(self.label_state_name, 1, 0, 1, 1)
        self.label_state = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_state.setFont(font)
        self.label_state.setText("")
        self.label_state.setObjectName("label_state")
        self.gridLayout_2.addWidget(self.label_state, 1, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 2, 0, 1, 2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Печать документа"))
        self.label_folfer_name.setText(_translate("Dialog", "Выбранная папка:"))
        self.label_state_name.setText(_translate("Dialog", "Текущий статус:"))
